# External Secrets Operator Placeholder
#
# This file serves as a placeholder to indicate that secrets are managed
# by External Secrets Operator, not by hardcoded values in Git.
#
# The actual SecretStore and ExternalSecret resources are created by Terraform
# in the test/external-secrets.tf file, which dynamically references:
# - Key Vault name from Terraform output
# - User Assigned Identity ID from AKS cluster
# - Tenant ID from Azure client config
#
# This approach ensures:
# ✅ No sensitive values stored in Git
# ✅ Dynamic configuration based on actual infrastructure
# ✅ Terraform manages the complete lifecycle
#
# To see the actual External Secrets configuration, check:
# - test/external-secrets.tf (Terraform resources)
# - kubectl get secretstore -n 3tirewebapp-test (runtime SecretStore)
# - kubectl get externalsecret -n 3tirewebapp-test (runtime ExternalSecret)

apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-management-info
  namespace: 3tirewebapp-test
data:
  secret-provider: "external-secrets-operator"
  managed-by: "terraform"
  note: "Sensitive values are dynamically managed by External Secrets Operator"
  documentation: "See test/external-secrets.tf for Terraform configuration"
